
(define (domain klotski_small)
(:requirements :strips)
(:predicates
	(at ?block ?pos)
	(free ?pos)
	(under ?pos1 ?pos2)
	(right ?pos1 ?pos2)
	(small ?block)
)

(:action move_small_up
:parameters (?free_pos ?old_pos ?s)
:precondition (and (free ?free_pos)
					(at ?s ?old_pos)
					(under ?old_pos ?free_pos)
					(small ?s))
:effect (and (free ?old_pos)
			 (at ?s ?free_pos)
			 (not (free ?free_pos))
			 (not (at ?s ?old_pos))))
(:action move_small_down
:parameters (?free_pos ?old_pos ?s)
:precondition (and (free ?free_pos)
					(at ?s ?old_pos)
					(under ?free_pos ?old_pos)
					(small ?s))
:effect (and (free ?old_pos)
			 (at ?s ?free_pos)
			 (not (free ?free_pos))
			 (not (at ?s ?old_pos))))
(:action move_small_right 
:parameters (?free_pos ?old_pos ?s)
:precondition (and (free ?free_pos)
				    (at ?s ?old_pos)
				    (right ?free_pos ?old_pos)
				    (small ?s))
:effect (and (free ?old_pos)
			 (at ?s ?free_pos)
			 (not (free ?free_pos))
			 (not (at ?s ?old_pos))))
)
(:action move_small_left 
:parameters (?free_pos ?old_pos ?s)
:precondition (and (free ?free_pos)
					(at ?s ?old_pos)
					(right ?old_pos ?free_pos)
					(small ?s))
:effect (and (free ?old_pos)
			 (at ?s ?free_pos)
			 (not (free ?free_pos))
			 (not (at ?s ?old_pos))))
)
