(define (domain klotski_medium)
(:requirements :strips)
(:predicates
	(at ?block ?pos)
	(free ?pos)
	(under ?pos1 ?pos2)
	(right ?pos1 ?pos2)
	(small ?block)
	(medium ?block)
	(long ?block)
	(big ?block)
)

(:action move_medium_down
:parameters (?free_pos ?old_pos1 ?old_pos2 ?m1)
:precondition (and (free ?free_pos)
				    (at ?m1 ?old_pos1)
				    (at ?m1 ?old_pos2)
				    (under ?old_pos2 ?old_pos1)
				    (under ?free_pos ?old_pos2)
				    (medium ?m1) )
:effect (and (free ?old_pos1)
			 (at ?m1 ?free_pos)
			 (not (free ?free_pos))
			 (not (at ?m1 ?old_pos1)) ))
(:action move_medium_right
:parameters (?free_pos1 ?free_pos2 ?old_pos1 ?old_pos2 ?m1)
:precondition (and (free ?free_pos1)
					(free ?free_pos2)
					(at ?m1 ?old_pos1)
					(at ?m1 ?old_pos2)
					(under ?free_pos2 ?free_pos1)
					(under ?old_pos2 ?old_pos1)
					(right ?free_pos1 ?old_pos1)
					(right ?free_pos2 ?old_pos2)
					(medium ?m1))
:effect (and (free ?old_pos1)
			 (free ?old_pos2)
			 (at ?m1 ?free_pos1)
			 (at ?m1 ?free_pos2)
			 (not (free ?free_pos1)
			 (not (free ?free_pos2) 
			 (not (at ?m1 ?old_pos1)
			 (not (at ?m1 ?old_pos2)) ))

)